import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Box, Flex, Spinner, Stack, Text } from "@chakra-ui/react";
import axios from "axios";
import { FiCalendar, FiDollarSign, FiTrendingUp } from "react-icons/fi";
import { useAuthState } from "../../../context/AuthProvider";
import EarningCard from "./EarningCard";
import {
  AdminEmptyState,
  AdminPageHero,
  AdminPanel,
} from "../../Admin/adminPageComponent/AdminLayout";

const formatAmount = (value) =>
  new Intl.NumberFormat("en-IN", {
    maximumFractionDigits: 0,
  }).format(Number(value || 0));

const Earning = () => {
  const [appoinments, setAppoinments] = useState([]);
  const [income, setIncome] = useState(0);
  const [clinicFee, setClinicFee] = useState(0);
  const [loading, setLoading] = useState(true);
  const { user } = useAuthState();

  const fetchAppoinments = useCallback(async () => {
    const token = user?.jwt;
    if (!token) return;

    setLoading(true);
    try {
      const { data } = await axios.get(
        `${process.env.REACT_APP_API_URL}/api/v1/booking/get-done-bookings`,
        {
          headers: {
            authorization: `Bearer ${token}`,
          },
        }
      );

      if (data.success !== false) {
        setAppoinments(Array.isArray(data?.appoinments) ? data.appoinments : []);
        setIncome(Number(data?.totalIncome || 0));
        setClinicFee(Number(data?.clinicFee ?? user?.clinicFee ?? 0));
      } else {
        setAppoinments([]);
        setIncome(0);
        setClinicFee(Number(user?.clinicFee || 0));
      }
    } catch (err) {
      console.log(err);
      setAppoinments([]);
      setIncome(0);
      setClinicFee(Number(user?.clinicFee || 0));
    } finally {
      setLoading(false);
    }
  }, [user?.clinicFee, user?.jwt]);

  useEffect(() => {
    fetchAppoinments();
  }, [fetchAppoinments]);

  const earningStats = useMemo(() => {
    const total = Number(income || 0);
    const completed = appoinments.length;
    const average = completed > 0 ? total / completed : Number(clinicFee || 0);

    return {
      total,
      completed,
      average,
      clinicFee: Number(clinicFee || 0),
    };
  }, [appoinments.length, clinicFee, income]);

  return (
    <Box w="full" maxW="1180px" mx="auto">
      <AdminPageHero
        badge="Doctor workspace"
        title="Your earnings"
        description="Track completed appointments, understand what they generate, and review the payment flow in a design that matches the rest of the workspace."
        stats={[
          {
            label: "Total income",
            value: `$ ${formatAmount(earningStats.total)}`,
            detail: "Revenue generated by completed bookings.",
            icon: FiDollarSign,
          },
          {
            label: "Completed visits",
            value: earningStats.completed,
            detail: "Paid appointments that have been settled.",
            icon: FiCalendar,
          },
          {
            label: "Average per visit",
            value: `$ ${formatAmount(earningStats.average)}`,
            detail: "The average revenue recorded per completed booking.",
            icon: FiTrendingUp,
          },
        ]}
      >
        <Box
          w={{ base: "full", xl: "290px" }}
          p={4}
          borderRadius="22px"
          bg="rgba(31, 58, 95, 0.04)"
          border="1px solid rgba(31, 58, 95, 0.08)"
        >
          <Text fontSize="sm" color="var(--regular-color)">
            Clinic fee
          </Text>
          <Text mt={1} fontSize="2xl" fontWeight="800" color="var(--heading-color)">
            $ {formatAmount(earningStats.clinicFee)}
          </Text>
          <Text fontSize="sm" color="var(--regular-color)" mt={2} lineHeight="1.6">
            Every completed booking contributes this fee to your total income.
          </Text>
          <Stack direction="row" spacing={2} mt={3} align="center">
            <Box
              as={FiDollarSign}
              color="var(--primary-green-color)"
              fontSize="14px"
            />
            <Text fontSize="sm" color="var(--heading-color)" fontWeight="700">
              {earningStats.completed} revenue entries
            </Text>
          </Stack>
        </Box>
      </AdminPageHero>

      <AdminPanel minH={{ base: "58vh", md: "64vh" }}>
        {loading ? (
          <Flex minH="48vh" align="center" justify="center">
            <Stack spacing={3} align="center" color="var(--heading-color)">
              <Spinner
                thickness="3px"
                speed="0.7s"
                color="var(--primary-green-color)"
                size="xl"
              />
              <Text fontWeight="700">Loading earnings...</Text>
            </Stack>
          </Flex>
        ) : appoinments.length > 0 ? (
          <Stack spacing={4}>
            {appoinments.map((appoinment, index) => (
              <EarningCard
                key={appoinment._id}
                appoinment={appoinment}
                index={index}
              />
            ))}
          </Stack>
        ) : (
          <AdminEmptyState
            title="No earnings yet"
            description="Once bookings are completed and marked as paid, they will appear here with a polished summary card."
          />
        )}
      </AdminPanel>
    </Box>
  );
};

export default Earning;
